### ISSUE TITLE
Inconsistent versions with Pip and Github source

### ISSUE THREAD

**Issue by aitoehigie** [Forethought-Technologies/AutoChain#111]
I noticed that the Autochain version available on Pip is not in sync with the source on GitHub.

For example, the Pip version doesn't have openai_functions_agent.

Is there a way I can help? Also, add versions/releases/tags here on GitHub?

**Comment by yyiilluu** [comment]
thanks for letting me know! i am going to work on setting up the version and releases soon. for now, i just published a new version 0.0.5 with the latest version
