### ISSUE TITLE
Can AutoChain be used in Production

### ISSUE THREAD

**Issue by aitoehigie** [Forethought-Technologies/AutoChain#119]
I read this announcement of AutoChain and noticed it harps on experimentation and flexibility.
I am curious, can AutoChain be used in production?

**Comment by yyiilluu** [comment]
AutoChain is designed to facilitate experimentations and don't plan to support complex engineering support for production in this repo. However, you are welcomed to add any needed production wirings to it for your own use cases, and it is under the very permissive MIT license
