### ISSUE TITLE
HuggingFaceTextGenerationModel as llm asks for OpenAI_API_KEY

### ISSUE THREAD

**Issue by tugrulguner** [Forethought-Technologies/AutoChain#125]
Hi,

I am planning to make a contribution to AutoChain at some point, and started to experiment a couple of things and getting myself familiar with the code.

I wanted to use open-source LLM from HuggingFace, so I figured out the HuggingFaceTextGenerationModel module, and created a simple script as:

```
from autochain.chain.chain import Chain
from autochain.memory.buffer_memory import BufferMemory
from autochain.models.huggingface_text_generation_model import HuggingFaceTextGenerationModel
from autochain.models.chat_openai import ChatOpenAI
from autochain.agent.conversational_agent.conversational_agent import ConversationalAgent

llm = HuggingFaceTextGenerationModel(model_name="distilgpt2")
memory = BufferMemory()
agent = ConversationalAgent.from_llm_and_tools(llm=llm)
chain = Chain(agent=agent, memory=memory)
print(chain.run("Write me a poem AI")['message'])
```

However this returns:
```
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Planning

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Invalid or incomplete response due to 'OPENAI_API_KEY'
Let me hand you off to an agent now
```

which I couldn't find where it is trying to grab OPENAI_API_KEY, I believe it is from the ConversationalAgent, but still couldn't figure out where to look at and where it goes wrong or maybe I am missing something and using some of those modules wrong.

**Comment by yyiilluu** [comment]
ah, good question. it is under `AgentOutputParser`, where i try to correct the json response from the model with OpenAI and make it a proper json afterwards. https://github.com/Forethought-Technologies/AutoChain/blob/main/autochain/agent/structs.py#L68-L78
however, this might not be ideal in the case where we don't want to have OpenAI at all. I can create a new output parser without such correction. 
For the time being, you could try to remove the correction from output parser to get around that. 

after testing it, i think the response you will get from distillgpt2 would not be great. the message would look something like this
```
AIMessage(content='Ensure the response can be parsed by Python json', additional_kwargs={}, example=False, function_call={})
```

**Comment by yyiilluu** [comment]
hope that answers your question
