### ISSUE TITLE
Support for Azure deployments

### ISSUE THREAD

**Issue by clemlesne** [Forethought-Technologies/AutoChain#95]
`deployment_id` and `model` parameters are required for OpenAI SDK to talk to OpenAI instances on Azure.

The error I have is:

```
exception=InvalidRequestError(message="Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>", param='engine', code=None, http_status=None, request_id=None)>
```

Integration examples:

```python
openai.Embedding.create(
  deployment_id="xxx",
  input=prompt,
  model="xxx",
)

completion = openai.ChatCompletion.create(
  deployment_id="xxx",
  messages=messages,
  model="xxx",
)
```

Proposed integration:

```python
ChatOpenAI(
  model_name="xxx",
  deployment_id="xxx",
  model="xxx",
)
```

**Comment by ChristianWeyer** [comment]
Yep, and we need to set the URL of the AOAI instance endpoint.

**Comment by tao12345666333** [comment]
I will submit a PR soon.

**Comment by tao12345666333** [comment]
I have submitted a PR to complete it.
https://github.com/Forethought-Technologies/AutoChain/pull/98

**Comment by yyiilluu** [comment]
great discussion here. let's add the support for it!
@tao12345666333 thank you for making the PR! I left some comments to your PR. let me know if you have any question

**Comment by tao12345666333** [comment]
Thanks, I left a comment
